### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by ghost** [IronistM/googleTagManageR#5]
Hi,

I'm trying to use the package but maybe I'm missing something. I keep getting a 403 response.

<img width="1034" alt="screen shot 2017-12-13 at 13 55 06" src="https://user-images.githubusercontent.com/8994002/33939958-683f1df0-e00d-11e7-8534-e291dab81ebb.png">

However, the API is enabled for my R client in GDS.

<img width="1148" alt="screen shot 2017-12-13 at 13 41 16" src="https://user-images.githubusercontent.com/8994002/33939973-7b8eaf42-e00d-11e7-918d-f8ddd7973205.png">

The app key URL is broken as well.

<img width="1917" alt="screen shot 2017-12-13 at 13 57 30" src="https://user-images.githubusercontent.com/8994002/33940016-a2ad0bc8-e00d-11e7-875c-e04b1412c599.png">

I do have Admin permission for the account I'm trying to retrieve. 

How can I solve this? 

Thanks.

**Comment by IronistM** [comment]
First of let's go through the steps for authentication

1. A client Id and secret generated via Create Credentials > OAuth client ID > Other - these are set in options(googleAuthR.client_id) and options(googleAuthR.client_secret), or if you download the client ID JSON using gar_set_client()
2. An API scope for the API you want to authenticate with, found in the APIs documentation or via the googleAuthR RStudio addin. In otu case something like this will be ok
```options(
  googleAuthR.scopes.selected =
    c(
      "https://www.googleapis.com/auth/webmasters",
      "https://www.googleapis.com/auth/analytics",
      "https://www.googleapis.com/auth/analytics.readonly",
      "https://www.googleapis.com/auth/devstorage.full_control",
      "https://www.googleapis.com/auth/tagmanager.readonly",
      "https://www.googleapis.com/auth/cloud-platform",
      "https://www.googleapis.com/auth/bigquery",
      "https://www.googleapis.com/auth/bigquery.insertdata"
    ),
  googleAuthR.client_id = 'SOMETHING.apps.googleusercontent.com',
  googleAuthR.client_secret = 'YOUR_SECRET'
)
```
3. A user authentication file, either generated interactivily via gar_auth() or via a service account file JSON file, created via Create credentials > Service account key.

Then you will get something like 
```R
> googleTagManageR::gtm_auth()
2017-12-14 10:56:16> Authenticated
Warning message:
In googleAuthR::gar_auto_auth(needed, new_user = new_user, no_auto = no_auto,  :
  travis_environment_var argument is now unsupported and does nothing
```

Ignore the warning and you should be all set! By the way the authntication URL should point to your locahost and not the URL shown in the attachment (whihc is the client ID)

**Comment by ghost** [comment]
Hi, Thank you so much!! It worked using the gtm_auth() 

I'm still trying to wrap my mind around the googleAuthR package. Much appreciated and thank you for creating your package.
